---
- name: Import the Redis APT key
  apt_key:
    url: https://packages.redis.io/gpg
    state: present
  become: true

- name: Install Redis deb repository
  apt_repository:
    repo: deb https://packages.redis.io/deb {{ ansible_distribution_release }} main
    state: present
  become: true

- name: Install Redis
  apt:
    name: redis-server
    update_cache: yes

- name: Install Redis Conf
  template:
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
    force: true
    owner: "redis"
    mode: 0644

- name: Install Redis Supervisord conf
  template:
    src: supervisor.conf.j2
    dest: /etc/supervisor/conf.d/redis.conf
    force: true
    mode: 0644

- name: Disable Redis services
  service:
    name: "{{ item }}"
    enabled: false
    state: stopped
  ignore_errors: true
  with_items:
    - "redis-server"
    - "redis"
