---
- name: Update apt repo and cache on all Ubuntu boxes
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600
    
- name: Set up Redis repo
  shell: |
    curl https://packages.redis.io/gpg | sudo apt-key add -
    echo "deb https://packages.redis.io/deb $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/redis.list

- name: Install Redis
  apt:
    name: redis-server
    update_cache: yes
  notify:
    - Enable Redis

- name: Install Redis Conf
  template:
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
    force: true
    owner: "redis"
    mode: 0644

- name: Install Redis Supervisord conf
  template:
    src: supervisor.conf.j2
    dest: /etc/supervisor/conf.d/redis.conf
    force: true
    mode: 0644

- name: Disable Redis services
  service:
    name: "{{ item }}"
    enabled: false
    state: stopped
  ignore_errors: true
  with_items:
    - "redis-server"
    - "redis"
