---

- name: Clear OPAM directory
  file:
    path: "{{ app_base }}/.opam"
    state: absent

- name: Download liblo
  get_url:
    url: https://github.com/radarsat1/liblo/releases/download/0.32/liblo-0.32.tar.gz
    dest: "/tmp/liblo-0.32.tar.gz"
    force: true

- name: Extract Liblo
  unarchive:
    src: "/tmp/liblo-0.32.tar.gz"
    dest: "/tmp/"
    remote_src: true

- name: Build liblo
  shell: "cd /tmp/liblo-0.32 && ./configure --prefix=/usr --libdir=/usr/lib64 && make && sudo make install"


- name: Download shine
  get_url:
    url: https://github.com/toots/shine/releases/download/3.1.1/shine-3.1.1.tar.gz
    dest: "/tmp/shine-3.1.1.tar.gz"
    force: true

- name: Extract shine
  unarchive:
    src: "/tmp/shine-3.1.1.tar.gz"
    dest: "/tmp/"
    remote_src: true
    mode: "u=rwx,g=rx,o=rx"
    owner: "azuracast"
    group: "www-data"

- name: Build shine
  shell: "cd /tmp/shine-3.1.1 && ./configure --prefix=/usr --libdir=/usr/lib64 && make && sudo make install"

- name: Link shine-conf
  file:
    src: /usr/lib64/pkgconfig/shine.pc
    dest: /usr/share/pkgconfig/shine.pc
    state: link

- shell: which opam
  become: false
  register: opam

- debug: msg={{ opam.stdout }}
  
- name: Install ocaml and audio packages (This can take quite a while...)
  become: true
  become_user: azuracast
  environment:
    OPAMYES: "1"
    PKG_CONFIG_PATH: "/usr/local/lib64/pkgconfig:/usr/local/lib/pkgconfig:/usr/lib64/pkgconfig:/usr/lib/pkgconfig"
    PATH: "/usr/local/bin:/usr/bin:/bin"
  shell: "{{item}}"
  with_items:
    - "{{opam.stdout}} init -a"
    - "{{opam.stdout}} install -y -q magic dune pulseaudio ao ogg srt ssl tsdl-image tsdl-ttf graphics taglib conf-freetype tls-liquidsoap opus taglib lilv mad lame faad speex imagelib theora vorbis gd flac fdkaac cry samplerate soundtouch lo shine conf-ffmpeg ffmpeg ffmpeg-av  ffmpeg-avcodec ffmpeg-avdevice ffmpeg-avfilter ffmpeg-avutil bjack portaudio ladspa sqlite3 liquidsoap.2.3.3"

- shell: eval `{{opam.stdout}} config env` && echo $OPAM_SWITCH_PREFIX
  become: true
  become_user: azuracast
  register: liquidsoap

- name: Create a symbolic link
  ansible.builtin.file:
    src: "{{liquidsoap.stdout}}/bin/liquidsoap"
    dest: /usr/local/bin/liquidsoap
    state: link


- name: Downloading tap-plugins
  ansible.builtin.git:
    repo: 'https://git.hq.sig7.se/tap-plugins.git'
    dest: /tmp/tap-plugins

- name: Build tap-plugins
  shell: "cd /tmp/tap-plugins && make"

- name: copy tap-plugins libs
  shell: "cd /tmp/tap-plugins && cp *.so /usr/lib64/ladspa && cp tap-plugins.rdf /usr/share/ladspa/rdf/ && cp tap_reverb.rdf /usr/share/ladspa/rdf/"


- name: Download lsp-plugins-ladspa
  get_url:
    url: https://github.com/sadko4u/lsp-plugins/releases/download/1.2.16/lsp-plugins-ladspa-1.2.16-Linux-{{ansible_architecture}}.tar.gz
    dest: "/tmp/lsp-plugins-ladspa-1.2.16-Linux-{{ansible_architecture}}.tar.gz"
    force: true

- name: Extract lsp-plugins-ladspa
  unarchive:
    src: "/tmp/lsp-plugins-ladspa-1.2.16-Linux-{{ansible_architecture}}.tar.gz"
    dest: "/tmp/"
    remote_src: true

- name: Copy lsp plugins
  ansible.builtin.copy:
    src: /tmp/lsp-plugins-ladspa-1.2.16-Linux-{{ansible_architecture}}/usr/lib/ladspa/
    dest: /usr/lib64/ladspa/lsp-plugins-ladspa.so


- name: Download swh-plugins-ladspa
  get_url:
    url: https://github.com/swh/ladspa/archive/refs/tags/v0.4.17.tar.gz
    dest: "/tmp/swh-plugins-ladspa.tar.gz"
    force: true

- name: Extract lsp-plugins-ladspa
  unarchive:
    src: "/tmp/swh-plugins-ladspa.tar.gz"
    dest: "/tmp/"
    remote_src: true

- name: Build lsp-plugins-ladspa
  shell: "cd /tmp/ladspa-0.4.17 && autoreconf -i && ./configure --prefix=/usr --libdir=/usr/lib64 && make && sudo make install"

- name: Create liquidsoap directory if it does not exist
  ansible.builtin.file:
    path: "{{app_base}}/liquidsoap"
    state: directory
    owner: azuracast
    group: azuracast

- name: Create liquidsoap directory if it does not exist
  ansible.builtin.file:
    path: "{{tmp_base}}/liquidsoap_cache"
    state: directory
    owner: azuracast
    group: azuracast

- name: Create liquidsoap directory if it does not exist
  ansible.builtin.file:
    path: "/tmp/liquidsoap_cache"
    state: directory
    owner: azuracast
    group: azuracast

- name: Write AzuraCast common liquidsoap config
  template:
    src: azuracast.liq.j2
    dest: "{{ app_base }}/liquidsoap/azuracast.liq"
    owner: azuracast
    group: azuracast
    mode: 0644
    force: true

- name: Write AzuraCast common liquidsoap config
  template:
    src: crossfade.liq.j2
    dest: "{{ app_base }}/liquidsoap/crossfade.liq"
    owner: azuracast
    group: azuracast
    mode: 0644
    force: true

- name: Write AzuraCast common liquidsoap config
  template:
    src: utilities.liq.j2
    dest: "{{ app_base }}/liquidsoap/utilities.liq"
    owner: azuracast
    group: azuracast
    mode: 0644
    force: true

#  @TODO: Find out if and which is required in this meta package and port those packages to RHEL
# - name: Install Optional Audio Plugins
#   apt:
#     name: "{{ packages }}"
#     install_recommends: false
#   vars:
#     packages:
#       - multimedia-audio-plugins
