---

- name: Detect if running under WSL
  command: systemd-detect-virt
  register: virt_detection
  changed_when: false


- name: Remove UFW
  dnf:
    name: "ufw"
    state: absent
  ignore_errors: true

- name: Set fact for WSL detection
  set_fact:
    is_wsl: "{{ virt_detection.stdout == 'wsl' }}"

- name: Execute tasks only if not running under WSL
  block:
    - name: Install Firewalld
      dnf:
        name: firewalld
        state: present

    - name: Ensure Firewalld service is started and enabled
      systemd:
        name: "firewalld"
        enabled: true
        state: started
      when: is_systemd == True

    - name: Firewalld - Enable AzuraCast TCP Ports
      firewalld:
        port: "{{ item }}"
        zone: public
        permanent: true
        state: enabled
      loop:
        - 80/tcp
        - 443/tcp
        - 2022/tcp
        - 8000-8999/tcp

    - name: Firewalld - Enable SSH
      firewalld:
        service: ssh
        zone: public
        permanent: true
        state: enabled

    - name: Always reload firewalld
      ansible.builtin.service:
        name: firewalld
        state: reloaded

    - name: Firewalld - Enable Firewall (if in production)
      firewalld:
        state: enabled
      when: app_env == "production"

    - name: Firewalld - Disable Firewall (if in development)
      firewalld:
        state: disabled
      when: app_env == "development"
  when: not is_wsl