---
- hosts: all
  become: true

  vars:
    ansible_base: "{{ playbook_dir | dirname }}"
    app_base: "{{ ansible_base | dirname }}"
    www_base: "{{ app_base }}/www"
    tmp_base: "{{ app_base }}/www_tmp"
    app_env: "production"
    update_mode: false
    dev_azuracast_user_password: "azuracast"
    dev_mysql_user_password: "azuracast"

  environment:
    DEBIAN_FRONTEND: noninteractive

  roles:
    - init
    - azuracast-user
    - azuracast-config
    - azuracast-radio
    - supervisord
    - nginx
    - php
    - redis
    - beanstalkd
    - sftpgo
    - mariadb
    - ufw
    - dbip
    - composer
    - services
    - azuracast-db-install
    - azuracast-build
    - azuracast-setup
    - azuracast-cron
