---

- hosts: all
  become: true

  collections:
    - community.general
  
  pre_tasks:
    - name: Load environment variables from .env file (if it exists)
      ansible.builtin.include_vars:
        file: "{{ playbook_dir | dirname }}/ansible/.env"
        name: env_vars
      ignore_errors: yes
  
  vars:
    ansible_base: "{{ playbook_dir | dirname }}"
    opam_version: "latest"
    opam_install_path: "/usr/local/bin/opam"
    opam_symlink_path: "/usr/bin/opam"
    opam_github_token: "{{ env_vars.GITHUB_TOKEN | default('') }}"
    app_base: "/var/azuracast" # IF YOU CHANGE THAT, BAD THINGS HAPPEN, CHECK TODO.md
    www_base: "{{ app_base }}/www"
    tmp_base: "{{ app_base }}/www_tmp"
    app_env: "production"
    update_mode: false
    dev_azuracast_user_password: "azuracast"
    dev_mysql_user_password: "azuracast"
    azuracast_repo: "{{ env_vars.AZURACAST_REPO | default('AzuraCast/AzuraCast') }}"
    azuracast_ref: "{{ env_vars.AZURACAST_REF | default('heads/') }}"
    azuracast_ver: "{{ env_vars.AZURACAST_VER | default('stable') }}"
    azuracast_dev_repo: "{{ env_vars.AZURACAST_DEV_REPO | default('AzuraCast/AzuraCast') }}"
    azuracast_dev_ver: "{{ env_vars.AZURACAST_DEV_VER | default('main') }}"

  roles:
    - role: init
      tags: init
    - role: azuracast-user
      tags: azuracast-user
    - role: azuracast-config
      tags: azuracast-config
    - role: opam
      tags: opam
    - role: azuracast-radio
      tags: azuracast-radio
    - role: supervisord
      tags: supervisord
    - role: nginx
      tags: nginx
    - role: php
      tags: php
    - role: redis
      tags: redis
    - role: centrifugo
      tags: centrifugo
    - role: sftpgo
      tags: sftpgo
    - role: mariadb
      tags: mariadb
    - role: ufw
      tags: ufw
    - role: dbip
      tags: dbip
    - role: composer
      tags: composer
    - role: azuracast-db-install
      tags: azuracast-db-install
    - role: services
      tags: services
      vars:
        run: "first"
    - role: azuracast-build
      tags: azuracast-build
    - role: azuracast-setup
      tags: azuracast-setup
    - role: azuracast-cron
      tags: azuracast-cron
    - role: services # We need this again to start newly added services
      tags: services
      vars:
        run: "second"
