---
- hosts: all
  become: true

  collections:
  - community.general
  
  pre_tasks:
    - name: Load environment variables from .env file (if it exists)
      ansible.builtin.include_vars:
        file: "{{ playbook_dir | dirname }}/ansible/.env"
        name: env_vars
      ignore_errors: yes

  vars:
    ansible_base: "{{ playbook_dir | dirname }}"
    app_base: "/var/azuracast"
    www_base: "{{ app_base }}/www"
    tmp_base: "{{ app_base }}/www_tmp"
    app_env: "production"
    update_mode: true
    update_revision: 5
    azuracast_repo: "{{ env_vars.AZURACAST_REPO | default('AzuraCast/AzuraCast') }}"
    azuracast_ref: "{{ env_vars.AZURACAST_REF | default('heads/') }}"
    azuracast_ver: "{{ env_vars.AZURACAST_VER | default('stable') }}"
    azuracast_dev_repo: "{{ env_vars.AZURACAST_DEV_REPO | default('AzuraCast/AzuraCast') }}"
    azuracast_dev_ver: "{{ env_vars.AZURACAST_DEV_VER | default('main') }}"

  roles:
    - role: "init"

    - role: "azuracast-config"

    - role: "azuracast-radio"
      when: update_revision|int < 6

    - role: "supervisord"

    - role: "nginx"
      when: update_revision|int < 6

    - role: "php"
      when: update_revision|int < 6

    - role: "redis"
      when: update_revision|int < 6

    - role: centrifugo
      when: update_revision|int < 6

    - role: "sftpgo"
      when: update_revision|int < 1

    - role: "mariadb"
      when: update_revision|int < 6

    - role: "ufw"
      when: update_revision|int < 3

    - role: "dbip"
      when: update_revision|int < 1

    - role: "composer"

    - role: "azuracast-cron"
      when: update_revision|int < 1

    - role: "services"
      vars:
        run: "first"

    - role: "azuracast-build"

    - role: "azuracast-setup"

    - role: services # We need this again to start newly added services
      vars:
        run: "second"
