---
- name: Install Composer
  shell: >-
    curl -fsSL https://getcomposer.org/installer
    | php -- --install-dir=/usr/bin --filename=composer
  args:
    warn: false

- name: Deploy AzuraCast Repository (Development)
  become: true
  become_user: azuracast
  command: >-
    composer create-project azuracast/azuracast:dev-main . --no-dev
  args:
    chdir: "{{ www_base }}"
  when: app_env == "development"

- name: Deploy AzuraCast Repository (Production)
  become: true
  become_user: azuracast
  command: >-
    composer create-project azuracast/azuracast:dev-main .
  args:
    chdir: "{{ www_base }}"
  when: app_env == "production"
