---
- name: Install supervisord from repo
  apt:
    name: supervisor

- name: Change supervisord configuration
  template:
    src: supervisord.conf.j2
    dest: /etc/supervisor/supervisord.conf
    force: true
    mode: 0644

- name: Temporarily turn off supervisord
  service:
    name: "supervisor"
    enabled: true
    state: stopped
  ignore_errors: true
